version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the source/ directory with Sphinx
sphinx:
  configuration: source/source_old/conf.py

python:
   install:
   - requirements: source/requirements.txt
