name: Run tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      env:
        OPN_API_KEY: ${{ vars.OPN_API_KEY }}
        OPN_API_SECRET: ${{ secrets.OPN_API_SECRET }}
        OPN_API_HOST: ${{ vars.OPN_API_HOST }}
        OPN_API_CA_CONTENT: ${{ vars.OPN_API_CA_CONTENT }}
        TEST_ALIAS: ${{ vars.TEST_ALIAS }}
        TEST_DOMAIN: ${{ vars.TEST_DOMAIN }}
        TEST_DOMAIN_IP: ${{ vars.TEST_DOMAIN_IP }}
      run: |
        pytest