name: Run tests
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        export OPN_API_KEY="${{ vars.OPN_API_KEY }}"
        export OPN_API_SECRET="${{ secrets.OPN_API_SECRET }}"
        export OPN_API_HOST="${{ vars.OPN_API_HOST }}"
        export OPN_API_CA_CONTENT="${{ vars.OPN_API_CA_CONTENT }}"
        export TEST_ALIAS="${{ vars.TEST_ALIAS }}"
        export TEST_DOMAIN="${{ vars.TEST_DOMAIN }}"
        export TEST_DOMAIN_IP="${{ vars.TEST_DOMAIN_IP }}"
        pytest